AWSTemplateFormatVersion: 2010-09-09
Description: (SO8019) - This template is used for setting up a EMR cluster. 
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - VPCID
      - PublicSubnet1ID
    - Label:
        default: Amazon EC2 configuration
      Parameters:
      - Ec2KeyName
    - Label:
        default: EMR configuration
      Parameters:
      - BootstrapBucket
    ParameterLabels:
      VPCID: 
        default: VPC ID
      PublicSubnet1ID:
        default: Public subnet 1 ID
Parameters: 
  VPCID:
    Description: Existing VPC ID.
    Type: AWS::EC2::VPC::Id
  PublicSubnet1ID:
    Description: Public subnet 1 ID.
    Type: AWS::EC2::Subnet::Id
  BootstrapBucket:
    Description: S3 bucket where EMR bootstrap script is located.
    Type: String
    Default: aws-quickstart-qiaow02
  EbsRootVolumeSize:
    Description: Size in GBs of EBS root volume.
    Type: String
    Default: 32
  Ec2KeyName:
    Description: EMR Master node SSH Keypair name.
    Type: AWS::EC2::KeyPair::KeyName
  MasterInstanceCount:
    Description: Number of Master nodes
    Type: Number
    Default: 1
  MasterInstanceType:
    Description: EC2 instance type for Master nodes
    Type: String
    Default: r5.2xlarge
  CoreInstanceCount:
    Description: Number of Core nodes
    Type: Number
    Default: 4
  CoreInstanceType:
    Description: EC2 instance type for Core nodes
    Type: String
    Default: r5.2xlarge
  ReleaseLabel:
    Description: Version of EMR to deploy to cluster
    Type: String
    Default: "emr-6.2.0"
  TerminationProtected:
    Description: Set auto-termination on or off
    Type: String
    Default: false
Resources:
  EmrCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: "aws-dc-nginx-emr-cluster"
      JobFlowRole: !Ref EmrEc2InstanceProfile
      ServiceRole: !Ref EmrRole
      AutoScalingRole: "EMR_AutoScaling_DefaultRole"
      Applications:
        - Name: "Ganglia"
        - Name: "Hadoop"
        - Name: "Spark"
        - Name: "Hive"
        - Name: "Zeppelin"
        - Name: "JupyterEnterpriseGateway"
      BootstrapActions:
        - Name: bootstrap-script
          ScriptBootstrapAction:
            Path: !Join ['', ['s3://', !Ref BootstrapBucket, '/bootstrap_actions.sh']]
      Configurations:
        - Classification: hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: 'com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory'
        - Classification: spark-hive-site
          ConfigurationProperties:
            hive.metastore.client.factory.class: 'com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory'
      EbsRootVolumeSize: !Ref EbsRootVolumeSize
      VisibleToAllUsers: true
      ReleaseLabel: !Ref ReleaseLabel
      LogUri: !Sub s3://${EmrLogsBucket}/
      Instances:
        Ec2SubnetId: !Ref PublicSubnet1ID
        Ec2KeyName: !Ref Ec2KeyName
        MasterInstanceGroup:
          InstanceCount: !Ref MasterInstanceCount
          InstanceType: !Ref MasterInstanceType
          Market: ON_DEMAND
          Name: MASTER
        CoreInstanceGroup:
          InstanceCount: !Ref CoreInstanceCount
          InstanceType: !Ref CoreInstanceType
          Market: ON_DEMAND
          Name: CORE
        TerminationProtected: !Ref TerminationProtected
  EmrLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ['-', ['aws-dc-nginx-emr', 'logs', !Ref 'AWS::AccountId', !Ref 'AWS::Region']]
      VersioningConfiguration:
        Status: Suspended
      Tags:
        - Key: Name
          Value: aws-dc-nginx
  EmrRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'EMR_DemoRole'
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole'
  EmrEc2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'EMR_EC2_DemoRole'
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role'
  EmrEc2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: 'EMR_EC2_DemoRole'
      Path: /
      Roles:
        - !Ref EmrEc2Role
